RealTimeBatteAngelRobot: rtblib.c File Reference
rtblib.c File Reference
#include "rtblib.h"
Functions
void nothing_action (robot_info *info)
void basic_initialize (robot_info *data_to_work)
void set_work_info (robot_info *data_to_work)
void set_message_action (enum message_to_robot_type code, type_action *action)
void set_strategy (type_action **strategy_actions)
enum message_to_robot_type name2msg_to_robot_type (char *msg_name)
void read_robot (int sig)
Variables
static type_action * actions [NUM_MESSAGES_TO_ROBOT]
static robot_info * work_info = 0
Function Documentation
void basic_initialize (robot_info * data_to_work)
initializes basic info values
Definition at line 39 of file rtblib.c.
References robot_info::cannonmaxrotate, robot_info::energy, robot_info::exit_robot, robot_info::maxenergy, robot_info::maxspeed, robot_info::minspeed, robot_info::radarmaxrotate, robot_info::robotmaxrotate, robot_info::shootpenalty, robot_info::shotmaxenergy, robot_info::shotminenergy, and robot_info::shotspeed.
Referenced by main().
enum message_to_robot_type name2msg_to_robot_type (char * msg_name)
converts a protocol message string into the code of the message
Definition at line 86 of file rtblib.c.
References message_to_robot, Message::msg, and UNKNOWN_MESSAGE_TO_ROBOT.
Referenced by read_robot().
void nothing_action (robot_info * info)
Definition at line 12 of file rtblib.c.
References debug().
void read_robot (int sig)
reads from the robot protocol use it to capture the read signal
Definition at line 101 of file rtblib.c.
References actions, robot_info::angle_pos, robot_info::cannonmaxrotate, COLLISION, COORDINATES, DEAD, debug(), robot_info::dist_to_object, robot_info::enemy_energy, ENERGY, robot_info::energy, EXIT_ROBOT, robot_info::exit_robot, GAME_FINISHES, GAME_OPTION, GAME_STARTS, INFO, INITIALIZE, robot_info::int_msg_value, robot_info::maxspeed, Message::msg, name2msg_to_robot_type(), NUM_MESSAGES_TO_ROBOT, robot_info::object_angle, robot_info::object_find, Print(), RADAR, robot_info::radarmaxrotate, read_robot(), ROBOT, ROBOT_CANNON_MAX_ROTATE, ROBOT_ENERGY_LEVELS, ROBOT_INFO, ROBOT_MAX_ACCELERATION, ROBOT_MAX_ENERGY, ROBOT_MAX_ROTATE, ROBOT_RADAR_MAX_ROTATE, ROBOT_START_ENERGY, robot_info::robotenergylevels, robot_info::robotmaxenergy, robot_info::robotmaxrotate, ROBOTS_LEFT, robot_info::robots_left, robot_info::robotstartenergy, ROTATION_REACHED, SHOT_ENERGY_INCREASE_SPEED, SHOT_MAX_ENERGY, SHOT_MIN_ENERGY, SHOT_SPEED, robot_info::shotenergyincreasespeed, robot_info::shotmaxenergy, robot_info::shotminenergy, robot_info::shotspeed, robot_info::speed, TIMEOUT, robot_info::timeout, WARNING, work_info, robot_info::x_pos, and robot_info::y_pos.
Referenced by main(), and read_robot().
void set_message_action (enum message_to_robot_type code, type_action * action)
sets the default action to do when message_to_robot_type code is received
Definition at line 66 of file rtblib.c.
References actions.
void set_strategy (type_action ** strategy_actions)
sets the strategy strategy_actions, the strategy defines an action to do for any message that can be received
Definition at line 75 of file rtblib.c.
References actions, and NUM_MESSAGES_TO_ROBOT.
Referenced by main().
void set_work_info (robot_info * data_to_work)
sets the robot_info variable where the data will be read
Definition at line 58 of file rtblib.c.
Referenced by main().
Variable Documentation
type_action* actions[NUM_MESSAGES_TO_ROBOT] static
Initial value:
{nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action,
                nothing_action
}
Definition at line 15 of file rtblib.c.
Referenced by read_robot(), set_message_action(), and set_strategy().
robot_info* work_info = 0 static
Definition at line 34 of file rtblib.c.
Referenced by read_robot().