RealTimeBatteAngelRobot: Include/rtblib.h File Reference
rtblib.h File Reference
#include <stdio.h>
Data Structures
struct Message
struct robot_info
Macros
#define ROTATE_ROBOT 1
#define ROTATE_CANNON 2
#define ROTATE_RADAR 4
#define ROTATE_ALL 7
#define PI 3.14159265358
#define NUM_MESSAGES_TO_ROBOT 17
Typedefs
typedef void(type_action)(robot_info *)
Enumerations
enum message_to_robot_type {
UNKNOWN_MESSAGE_TO_ROBOT = -1, INITIALIZE, YOUR_NAME, YOUR_COLOUR,
GAME_OPTION, GAME_STARTS, RADAR, INFO,
COORDINATES, ROBOT_INFO, ROTATION_REACHED, ENERGY,
ROBOTS_LEFT, COLLISION, WARNING, DEAD,
GAME_FINISHES, EXIT_ROBOT
}
enum message_from_robot_type {
UNKNOWN_MESSAGE_FROM_ROBOT = -1, ROBOT_OPTION, NAME, COLOUR,
ROTATE, ROTATE_TO, ROTATE_AMOUNT, SWEEP,
ACCELERATE, BRAKE, BREAK, SHOOT,
PRINT, DEBUG, DEBUG_LINE, DEBUG_CIRCLE
}
enum argument_type {
NONE, STRING, DOUBLE, INT,
HEX
}
enum warning_type {
UNKNOWN_MESSAGE = 0, PROCESS_TIME_LOW = 1, MESSAGE_SENT_IN_ILLEGAL_STATE = 2, UNKNOWN_OPTION = 3,
OBSOLETE_KEYWORD = 4, NAME_NOT_GIVEN = 5, COLOUR_NOT_GIVEN = 6
}
enum game_option_type {
ROBOT_MAX_ROTATE = 0, ROBOT_CANNON_MAX_ROTATE = 1, ROBOT_RADAR_MAX_ROTATE = 2, ROBOT_MAX_ACCELERATION = 3,
ROBOT_MIN_ACCELERATION = 4, ROBOT_START_ENERGY = 5, ROBOT_MAX_ENERGY = 6, ROBOT_ENERGY_LEVELS = 7,
SHOT_SPEED = 8, SHOT_MIN_ENERGY = 9, SHOT_MAX_ENERGY = 10, SHOT_ENERGY_INCREASE_SPEED = 11,
TIMEOUT = 12, DEBUG_LEVEL = 13, SEND_ROBOT_COORDINATES = 14
}
enum robot_option_type { SIGNAL = 2, SEND_SIGNAL = 0, SEND_ROTATION_REACHED = 1, USE_NON_BLOCKING = 3 }
enum object_type {
NOOBJECT = -1, ROBOT = 0, SHOT = 1, WALL = 2,
COOKIE = 3, MINE = 4, LAST_OBJECT_TYPE = 5
}
Functions
static void debug (const char *msg)
static void Print (const char *msg)
static void robot_option (int option, int value)
static void colour (const char *color1, const char *color2)
static void name (const char *name)
static void accelerate (const double accel)
static void rotate (const int what, const double angular_speed)
static void shoot (const double shoot_energy)
static void rotate_to (const int what, const double angular_speed, const double end_angle)
static void sweep (const int what, const double angular_speed, const double left, const double right)
static void rotate_amount (const int what, const double angular_speed, const double angle)
static void brake (const double portion)
enum message_to_robot_type name2msg_to_robot_type (char *msg_name)
void read_robot (int sig)
void set_work_info (robot_info *data_to_work)
void set_message_action (enum message_to_robot_type code, type_action *action)
void set_strategy (type_action **strategy_actions)
void basic_initialize (robot_info *data_to_work)
Variables
static const int number_of_object_types = 5
static struct Message message_to_robot [25]
static struct Message message_from_robot [25]
Macro Definition Documentation
#define NUM_MESSAGES_TO_ROBOT 17
Definition at line 60 of file rtblib.h.
Referenced by read_robot(), and set_strategy().
#define PI 3.14159265358
Definition at line 31 of file rtblib.h.
Referenced by search_destroy_do_collision(), search_destroy_do_game_starts(), and search_destroy_do_radar().
#define ROTATE_ALL 7
Definition at line 30 of file rtblib.h.
Referenced by search_destroy_do_collision(), and search_destroy_do_radar().
#define ROTATE_CANNON 2
Definition at line 28 of file rtblib.h.
Referenced by search_destroy_do_collision(), search_destroy_do_game_starts(), search_destroy_do_info(), and search_destroy_do_radar().
#define ROTATE_RADAR 4
Definition at line 29 of file rtblib.h.
Referenced by search_destroy_do_collision(), search_destroy_do_game_starts(), search_destroy_do_info(), and search_destroy_do_radar().
#define ROTATE_ROBOT 1
Definition at line 27 of file rtblib.h.
Referenced by search_destroy_do_collision(), and search_destroy_do_radar().
Typedef Documentation
typedef void(type_action)(robot_info *)
Definition at line 268 of file rtblib.h.
Enumeration Type Documentation
enum argument_type
Enumerator:
NONE
STRING
DOUBLE
INT
HEX
Definition at line 87 of file rtblib.h.
enum game_option_type
Enumerator:
ROBOT_MAX_ROTATE
ROBOT_CANNON_MAX_ROTATE
ROBOT_RADAR_MAX_ROTATE
ROBOT_MAX_ACCELERATION
ROBOT_MIN_ACCELERATION
ROBOT_START_ENERGY
ROBOT_MAX_ENERGY
ROBOT_ENERGY_LEVELS
SHOT_SPEED
SHOT_MIN_ENERGY
SHOT_MAX_ENERGY
SHOT_ENERGY_INCREASE_SPEED
TIMEOUT
DEBUG_LEVEL
SEND_ROBOT_COORDINATES
Definition at line 110 of file rtblib.h.
enum message_from_robot_type
Enumerator:
UNKNOWN_MESSAGE_FROM_ROBOT
ROBOT_OPTION
NAME
COLOUR
ROTATE
ROTATE_TO
ROTATE_AMOUNT
SWEEP
ACCELERATE
BRAKE
BREAK
SHOOT
PRINT
DEBUG
DEBUG_LINE
DEBUG_CIRCLE
Definition at line 62 of file rtblib.h.
enum message_to_robot_type
Enumerator:
UNKNOWN_MESSAGE_TO_ROBOT
INITIALIZE
YOUR_NAME
YOUR_COLOUR
GAME_OPTION
GAME_STARTS
RADAR
INFO
COORDINATES
ROBOT_INFO
ROTATION_REACHED
ENERGY
ROBOTS_LEFT
COLLISION
WARNING
DEAD
GAME_FINISHES
EXIT_ROBOT
Definition at line 34 of file rtblib.h.
enum object_type
Enumerator:
NOOBJECT
ROBOT
SHOT
WALL
COOKIE
MINE
LAST_OBJECT_TYPE
Definition at line 150 of file rtblib.h.
enum robot_option_type
Enumerator:
SIGNAL
SEND_SIGNAL
SEND_ROTATION_REACHED
USE_NON_BLOCKING
Definition at line 137 of file rtblib.h.
enum warning_type
Enumerator:
UNKNOWN_MESSAGE
PROCESS_TIME_LOW
MESSAGE_SENT_IN_ILLEGAL_STATE
UNKNOWN_OPTION
OBSOLETE_KEYWORD
NAME_NOT_GIVEN
COLOUR_NOT_GIVEN
Definition at line 97 of file rtblib.h.
Function Documentation
static void accelerate (const double accel) inline static
Definition at line 301 of file rtblib.h.
Referenced by search_destroy_do_collision(), search_destroy_do_game_starts(), and search_destroy_do_radar().
void basic_initialize (robot_info * data_to_work)
initializes basic info values
Definition at line 39 of file rtblib.c.
References robot_info::cannonmaxrotate, robot_info::energy, robot_info::exit_robot, robot_info::maxenergy, robot_info::maxspeed, robot_info::minspeed, robot_info::radarmaxrotate, robot_info::robotmaxrotate, robot_info::shootpenalty, robot_info::shotmaxenergy, robot_info::shotminenergy, and robot_info::shotspeed.
Referenced by main().
static void brake (const double portion) inline static
Definition at line 337 of file rtblib.h.
Referenced by search_destroy_do_collision(), and search_destroy_do_radar().
static void colour (const char * color1, const char * color2) inline static
Definition at line 289 of file rtblib.h.
Referenced by search_destroy_do_initialize().
static void debug (const char * msg) inline static
Definition at line 271 of file rtblib.h.
Referenced by nothing_action(), read_robot(), search_destroy_do_initialize(), and search_destroy_do_nothing().
static void name (const char * name) inline static
Definition at line 295 of file rtblib.h.
Referenced by search_destroy_do_initialize().
enum message_to_robot_type name2msg_to_robot_type (char * msg_name)
converts a protocol message string into the code of the message
Definition at line 86 of file rtblib.c.
References message_to_robot, Message::msg, and UNKNOWN_MESSAGE_TO_ROBOT.
Referenced by read_robot().
static void Print (const char * msg) inline static
Definition at line 277 of file rtblib.h.
Referenced by read_robot(), search_destroy_do_collision(), search_destroy_do_game_starts(), and search_destroy_do_radar().
void read_robot (int sig)
reads from the robot protocol use it to capture the read signal
Definition at line 101 of file rtblib.c.
References actions, robot_info::angle_pos, robot_info::cannonmaxrotate, COLLISION, COORDINATES, DEAD, debug(), robot_info::dist_to_object, robot_info::enemy_energy, ENERGY, robot_info::energy, EXIT_ROBOT, robot_info::exit_robot, GAME_FINISHES, GAME_OPTION, GAME_STARTS, INFO, INITIALIZE, robot_info::int_msg_value, robot_info::maxspeed, Message::msg, name2msg_to_robot_type(), NUM_MESSAGES_TO_ROBOT, robot_info::object_angle, robot_info::object_find, Print(), RADAR, robot_info::radarmaxrotate, read_robot(), ROBOT, ROBOT_CANNON_MAX_ROTATE, ROBOT_ENERGY_LEVELS, ROBOT_INFO, ROBOT_MAX_ACCELERATION, ROBOT_MAX_ENERGY, ROBOT_MAX_ROTATE, ROBOT_RADAR_MAX_ROTATE, ROBOT_START_ENERGY, robot_info::robotenergylevels, robot_info::robotmaxenergy, robot_info::robotmaxrotate, ROBOTS_LEFT, robot_info::robots_left, robot_info::robotstartenergy, ROTATION_REACHED, SHOT_ENERGY_INCREASE_SPEED, SHOT_MAX_ENERGY, SHOT_MIN_ENERGY, SHOT_SPEED, robot_info::shotenergyincreasespeed, robot_info::shotmaxenergy, robot_info::shotminenergy, robot_info::shotspeed, robot_info::speed, TIMEOUT, robot_info::timeout, WARNING, work_info, robot_info::x_pos, and robot_info::y_pos.
Referenced by main(), and read_robot().
static void robot_option (int option, int value) inline static
Definition at line 283 of file rtblib.h.
Referenced by main().
static void rotate (const int what, const double angular_speed) inline static
Definition at line 307 of file rtblib.h.
Referenced by search_destroy_do_collision(), and search_destroy_do_radar().
static void rotate_amount (const int what, const double angular_speed, const double angle) inline static
Definition at line 331 of file rtblib.h.
Referenced by search_destroy_do_collision(), and search_destroy_do_radar().
static void rotate_to (const int what, const double angular_speed, const double end_angle) inline static
Definition at line 319 of file rtblib.h.
Referenced by search_destroy_do_collision(), search_destroy_do_info(), and search_destroy_do_radar().
void set_message_action (enum message_to_robot_type code, type_action * action)
sets the default action to do when message_to_robot_type code is received
Definition at line 66 of file rtblib.c.
References actions.
void set_strategy (type_action ** strategy_actions)
sets the strategy strategy_actions, the strategy defines an action to do for any message that can be received
Definition at line 75 of file rtblib.c.
References actions, and NUM_MESSAGES_TO_ROBOT.
Referenced by main().
void set_work_info (robot_info * data_to_work)
sets the robot_info variable where the data will be read
Definition at line 58 of file rtblib.c.
Referenced by main().
static void shoot (const double shoot_energy) inline static
Definition at line 313 of file rtblib.h.
Referenced by search_destroy_do_collision(), and search_destroy_do_radar().
static void sweep (const int what, const double angular_speed, const double left, const double right) inline static
Definition at line 325 of file rtblib.h.
Referenced by search_destroy_do_game_starts().
Variable Documentation
struct Message message_from_robot[25] static
Initial value:
{
  {"RobotOption",  2, {INT, INT}},
  {"Name",         1, {STRING}},
  {"Colour",       2, {HEX, HEX}},
  {"Rotate",       2, {INT, DOUBLE}},
  {"RotateTo",     3, {INT, DOUBLE, DOUBLE}},
  {"RotateAmount", 3, {INT, DOUBLE, DOUBLE}},
  {"Sweep",        4, {INT, DOUBLE, DOUBLE, DOUBLE}},
  {"Accelerate", 1, {DOUBLE}},
  {"Brake",        1, {DOUBLE}},
  {"Break",        1, {DOUBLE}},
  {"Shoot",        1, {DOUBLE}},
  {"Print",        1, {STRING}},
  {"Debug",        1, {STRING}},
  {"DebugLine",    4, {DOUBLE, DOUBLE, DOUBLE, DOUBLE}},
  {"DebugCircle",  3, {DOUBLE, DOUBLE, DOUBLE}},
  {"",             0, {}}
}
Definition at line 198 of file rtblib.h.
struct Message message_to_robot[25] static
Initial value:
{
  {"Initialize", 1, {INT,    NONE,   NONE,   NONE}},
  {"YourName",   1, {STRING, NONE,   NONE,   NONE}},
  {"YourColour", 1, {HEX,    NONE,   NONE,   NONE}},
  {"GameOption", 2, {INT,    DOUBLE, NONE,   NONE}},
  {"GameStarts", 0, {NONE,   NONE,   NONE,   NONE}},
  {"Radar",      3, {DOUBLE, INT,    DOUBLE, NONE}},
  {"Info",       3, {DOUBLE, DOUBLE, DOUBLE, NONE}},
  {"Coordinates",3, {DOUBLE, DOUBLE, DOUBLE, NONE}},
  {"RobotInfo",  2, {DOUBLE, INT,    NONE,   NONE}},
  {"RotationReached",1,{INT, NONE,  NONE,   NONE}},
  {"Energy",     1, {DOUBLE, NONE,   NONE,   NONE}},
  {"RobotsLeft", 1, {INT,    NONE,   NONE,   NONE}},
  {"Collision",  2, {INT,    DOUBLE, NONE,   NONE}},
  {"Warning",    2, {INT,    STRING, NONE,   NONE}},
  {"Dead",       0, {NONE,   NONE,   NONE,   NONE}},
  {"GameFinishes",0,{NONE,   NONE,   NONE,   NONE}},
  {"ExitRobot",  0, {NONE,   NONE,   NONE,   NONE}},
  {"",           0, {}}
}
Definition at line 170 of file rtblib.h.
Referenced by name2msg_to_robot_type().
const int number_of_object_types = 5 static
Definition at line 161 of file rtblib.h.