RealTimeBatteAngelRobot: search_destroy_strategy/search_destroy_strategy.c File Reference
search_destroy_strategy.c File Reference
#include <stdlib.h>
#include "rtblib.h"
Macros
#define NOTHING 0
#define GET_COOKIE 1
Functions
void search_destroy_do_nothing (robot_info *info)
void search_destroy_do_game_starts (robot_info *info)
void search_destroy_do_info (robot_info *info)
void search_destroy_do_radar (robot_info *info)
void search_destroy_do_collision (robot_info *info)
void search_destroy_do_initialize (robot_info *info)
void search_destroy_do_rotation_reached (robot_info *info)
type_action ** get_search_destroy_strategy (void)
Variables
static type_action * search_destroy_strategy [NUM_MESSAGES_TO_ROBOT]
Macro Definition Documentation
#define GET_COOKIE 1
Referenced by search_destroy_do_radar().
#define NOTHING 0
Referenced by search_destroy_do_radar().
Function Documentation
type_action** get_search_destroy_strategy (void)
gets the search destroy strategy
Definition at line 216 of file search_destroy_strategy.c.
References COLLISION, COORDINATES, DEAD, ENERGY, EXIT_ROBOT, GAME_FINISHES, GAME_OPTION, GAME_STARTS, INFO, INITIALIZE, RADAR, ROBOT_INFO, ROBOTS_LEFT, ROTATION_REACHED, search_destroy_do_collision(), search_destroy_do_game_starts(), search_destroy_do_info(), search_destroy_do_initialize(), search_destroy_do_nothing(), search_destroy_do_radar(), search_destroy_do_rotation_reached(), search_destroy_strategy, WARNING, YOUR_COLOUR, and YOUR_NAME.
Referenced by main().
void search_destroy_do_collision (robot_info * info)
Definition at line 132 of file search_destroy_strategy.c.
References accelerate(), brake(), robot_info::cannonmaxrotate, COOKIE, robot_info::dist_to_object, robot_info::energy, robot_info::maxspeed, robot_info::object_angle, robot_info::object_find, PI, Print(), ROBOT, robot_info::robotmaxenergy, robot_info::robotmaxrotate, rotate(), ROTATE_ALL, rotate_amount(), ROTATE_CANNON, ROTATE_RADAR, ROTATE_ROBOT, rotate_to(), shoot(), SHOT, robot_info::shotmaxenergy, robot_info::speed, and WALL.
Referenced by get_search_destroy_strategy().
void search_destroy_do_game_starts (robot_info * info)
Definition at line 20 of file search_destroy_strategy.c.
References accelerate(), robot_info::maxspeed, PI, Print(), ROTATE_CANNON, ROTATE_RADAR, and sweep().
Referenced by get_search_destroy_strategy().
void search_destroy_do_info (robot_info * info)
Definition at line 27 of file search_destroy_strategy.c.
References ROTATE_CANNON, ROTATE_RADAR, and rotate_to().
Referenced by get_search_destroy_strategy().
void search_destroy_do_initialize (robot_info * info)
Definition at line 195 of file search_destroy_strategy.c.
References colour(), debug(), robot_info::int_msg_value, and name().
Referenced by get_search_destroy_strategy().
void search_destroy_do_nothing (robot_info * info)
Definition at line 15 of file search_destroy_strategy.c.
References debug().
Referenced by get_search_destroy_strategy().
void search_destroy_do_radar (robot_info * info)
Definition at line 31 of file search_destroy_strategy.c.
References accelerate(), brake(), robot_info::cannonmaxrotate, COOKIE, robot_info::dist_to_object, robot_info::energy, GET_COOKIE, robot_info::maxspeed, MINE, NOTHING, robot_info::object_angle, robot_info::object_find, PI, Print(), ROBOT, robot_info::robotmaxenergy, robot_info::robotmaxrotate, robot_info::robots_left, rotate(), ROTATE_ALL, rotate_amount(), ROTATE_CANNON, ROTATE_RADAR, ROTATE_ROBOT, rotate_to(), shoot(), SHOT, robot_info::shotmaxenergy, robot_info::shotminenergy, robot_info::speed, and WALL.
Referenced by get_search_destroy_strategy().
void search_destroy_do_rotation_reached (robot_info * info)
Definition at line 206 of file search_destroy_strategy.c.
Referenced by get_search_destroy_strategy().
Variable Documentation
type_action* search_destroy_strategy[NUM_MESSAGES_TO_ROBOT] static
Definition at line 211 of file search_destroy_strategy.c.
Referenced by get_search_destroy_strategy().