RealTimeBatteAngelRobot: Include/search_destroy_strategy/search_destroy_strategy.h File Reference
search_destroy_strategy.h File Reference
Functions
type_action ** get_search_destroy_strategy (void)
Function Documentation
type_action** get_search_destroy_strategy (void)
gets the search destroy strategy
Definition at line 216 of file search_destroy_strategy.c.
References COLLISION, COORDINATES, DEAD, ENERGY, EXIT_ROBOT, GAME_FINISHES, GAME_OPTION, GAME_STARTS, INFO, INITIALIZE, RADAR, ROBOT_INFO, ROBOTS_LEFT, ROTATION_REACHED, search_destroy_do_collision(), search_destroy_do_game_starts(), search_destroy_do_info(), search_destroy_do_initialize(), search_destroy_do_nothing(), search_destroy_do_radar(), search_destroy_do_rotation_reached(), search_destroy_strategy, WARNING, YOUR_COLOUR, and YOUR_NAME.
Referenced by main().